name: Lint

on:
  push: { }
  pull_request: { }

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: "1.25.1"

      - name: Run ui build
        run: make ui-build

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.4

      - name: Run lint
        run: make lint

      - name: Run check
        run: make check

      - name: Run test
        run: make test

      - name: Run build
        run: make build
